### ISSUE TITLE
The following page says there are more free offers, but in reality there are no offers listed below.

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#1]
## The following page says there are more free offers, but in reality there are no offers listed below

![issue-1](https://cloud.githubusercontent.com/assets/15894297/11519653/f2879188-9869-11e5-9e42-52fd3cdd0485.png)

**Comment by andreat-lj** [comment]
Cannot reproduce error. There was a server migration that may have been the cause of this temporary issue.

![15-12-09 ff cpl demo](https://cloud.githubusercontent.com/assets/16214350/11693139/37166164-9e71-11e5-80de-394444e4963a.png)

**Comment by andrewkhomski** [comment]
This is correct. At this point i also can't replicate the issue. Closing.
