### ISSUE TITLE
IE: On the 1166 the text on the clip gets crazy - see attached

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#10]
I was trying to rewind clip a bit forward on this 1166.
IE: On the 1166 the text on the clip gets crazy.

![issue-9](https://cloud.githubusercontent.com/assets/15894297/11520166/dc76b806-986e-11e5-8238-9ab26c2aec59.png)

**Comment by andreat-lj** [comment]
This domain is not hosted by us.

**Comment by andrewkhomski** [comment]
OK. I have to go with your verdict. Closing this DF.
