### ISSUE TITLE
IE: The error message if user clicks on the buttons second time (1118)

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#11]
## IE: There is an error message if user clicks on the buttons second time (1118)

If you are on this page:
**http://www.marketdeal.com/cplplusdemo/?email=test@test.com&fn=David&override=1118**

Now you click on the "Access this Trade Opportunity Here".
This page will appear:
**http://pro.moneymappress.com/TIMBANZAIGI/PTIMRB01/?h=true**

Navigate within it - scroll on it.
Now go back to the first page and click on the same button again ( "Access this Trade Opportunity Here").
Observe the error.

![issue-10](https://cloud.githubusercontent.com/assets/15894297/11520229/7591bcb6-986f-11e5-8c80-eb75379ccda0.png)

**Comment by andreat-lj** [comment]
Cannot duplicate error in Chrome, Firefox, or Internet Explorer.

**Comment by andrewkhomski** [comment]
Andrea - you are correct - i am not able to replicate this issue at this point. Closing these DFs
