### ISSUE TITLE
Chrome: Button is not clickable in Chrome for 1039

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#12]
## Chrome: Button is not clickable in Chrome for 1039

Button is only clickable where the text is - but not clickable within the entire perimeter of the button.

![issue-11](https://cloud.githubusercontent.com/assets/15894297/11520311/4f144d6e-9870-11e5-8ed1-c26efe96ee2d.png)

**Comment by andreat-lj** [comment]
http://www.marketdeal.com/cplplusdemo/?email=test-1215@finmc.com&name=test&override=1186

Updated. Clickable link now extends full button width. Added some top & bottom padding as well.

**Comment by andrewkhomski** [comment]
I verified this fix and now the issue is resolved. Closing.
