### ISSUE TITLE
Link is not clickable from the 1st time (1045)

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#13]
## Link is not clickable from the 1st time (1045)

![issue-12](https://cloud.githubusercontent.com/assets/15894297/11520340/ad6f979c-9870-11e5-9e39-914002499924.png)

**Comment by andreat-lj** [comment]
http://www.marketdeal.com/cplplusdemo/?email=test-1215@finmc.com&name=test&override=1045

Link is clickable from the start as long as the user waits ~5 seconds for page to finish loading first. This ad requires a geocheck which takes a few seconds to complete & causes browser to interpret the delay as a pop-up ad.

**Comment by andrewkhomski** [comment]
I see it works now - closing this Defect.
