### ISSUE TITLE
Firefox: Error on 1118.

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#22]
## Also get this errors on 1118

![issue-18](https://cloud.githubusercontent.com/assets/15894297/11520709/f48e6a88-9873-11e5-982f-e7920223616c.png)

![issue-18a](https://cloud.githubusercontent.com/assets/15894297/11520710/f48eca3c-9873-11e5-9897-3ccbdb867d3b.png)

**Comment by andreat-lj** [comment]
Cannot duplicate error.

![15-12-15 9-35](https://cloud.githubusercontent.com/assets/16214350/11813416/66af0730-a30f-11e5-9f05-080b864cf110.png)

**Comment by andrewkhomski** [comment]
Seems to work now. Closing this Defect. Will re-open if issue comes back.
