### ISSUE TITLE
IE: The "Sorry. This seminar is over." message appear, when click on unique webinar link (1100)

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#26]
## IE: The "Sorry. This seminar is over." message appear, when click on unique webinar link

Your unique webinar link: http://www.onlinemeetingnow.com/seminar/?id=r0zlurhwyg&email=test@test.com&name=David

![issue-22](https://cloud.githubusercontent.com/assets/15894297/11550134/a0ea51d6-993a-11e5-9f0c-a3e3601d0881.png)

**Comment by andreat-lj** [comment]
Cannot duplicate error.
http://www.marketdeal.com/cplplusdemo/?email=test-1215@finmc.com&name=test&override=1100

![15-12-15 9-22](https://cloud.githubusercontent.com/assets/16214350/11813114/7773d8d6-a30d-11e5-8ca6-56d495b3c9fd.png)

**Comment by andrewkhomski** [comment]
This is correct - at this point the issue seems to be resolved. Closing.
