### ISSUE TITLE
Chrome: Error "Confirm Form Re-submission" when click on BACK button (1205)

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#28]
## Chrome: Error "Confirm Form Re-submission" when click on BACK button

URL in trouble:
## https://go.pardot.com/l/26072/2015-04-02/3n5887

Confirm Form Resubmission

ERR_CACHE_MISS
Hide details
This webpage requires data that you entered earlier in order to be properly displayed. You can send this data again, but by doing so you will repeat any action this page previously performed.
Reload this webpage
Press the reload button to resubmit the data needed to load the page.
## ![issue-24](https://cloud.githubusercontent.com/assets/15894297/11605209/00e980fa-9ac8-11e5-991c-c610ef232187.png)

STEPS:
1) From this page - click on "I want MY Consultation":
https://lp.optionsanimal.com/ib/bh3/bh3-p2-2015-11-29-fmc-cpl-plus.html
2) In the "Take your Trading to the Next Level" click on the **Start My Consultation** button
3) Click on the **Free Consultation** button on this page (don't enter any data)
https://go.pardot.com/l/26072/2015-04-02/3n5887
4) Click on the Back button of the browser
5) Observe the error page

**Comment by andreat-lj** [comment]
This domain is not hosted by us.

**Comment by andrewkhomski** [comment]
I cannot argue with that - closing this Defect as not an issue.
