### ISSUE TITLE
MOBILE (Android): The position of the buttons

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#3]
## Need to confirm the position of the buttons as expected for mobile (Android).

![issue-3](https://cloud.githubusercontent.com/assets/15894297/11519796/04b47866-986b-11e5-975c-d258bcce1510.png)

**Comment by andreat-lj** [comment]
Confirmed with Harry that this is the correct android placement.

**Comment by andrewkhomski** [comment]
Thank you! Closing.
