### ISSUE TITLE
On the 1216, 1223 & 1229 - all 4 buttons are link to the same content

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#30]
## On the 1216, 1223 and 1229 - all 4 buttons are link to the same content

No matter if click on the STOCKS, FUTURES, ENERGY or FOREX - the content displayed always for FOREX:
**THE 10 KEYS TO SUCCESSFUL FOREX TRADING**

**Comment by andreat-lj** [comment]
The following links appear to be working properly. I confirmed that the displayed offers correspond to the correct offer IDs. Please just let me know if I need to look at this differently.

http://www.marketdeal.com/cplplusdemo/?email=test-1214@finmc.com&name=test&override=1216
http://www.marketdeal.com/cplplusdemo/?email=test-1214@finmc.com&name=test&override=1223
http://www.marketdeal.com/cplplusdemo/?email=test-1214@finmc.com&name=test&override=1229

**Comment by andrewkhomski** [comment]
Yes. If it is correct content - i am closing this defect. Just looked odd that the names of the offers are different but the content is the same...

**Comment by andreat-lj** [comment]
Just to clarify... Each of the 3 offers differs from the other 2. However, when an override=0000 parameter is set, all four market buttons will lead to the same 'override' content for testing purposes. Does this explanation correctly address the question?

![image](https://cloud.githubusercontent.com/assets/16214350/11934575/1fe194d2-a7d1-11e5-9ec3-3ce22ffe90d5.png)

![image](https://cloud.githubusercontent.com/assets/16214350/11934586/34853cae-a7d1-11e5-822c-3fcccf497a0a.png)

![image](https://cloud.githubusercontent.com/assets/16214350/11934600/440edb44-a7d1-11e5-959f-44210a97d929.png)

**Comment by andrewkhomski** [comment]
Thank you Andrea

I have a question - does it require for me to test with override set to
0000?

I would assume it is better to have the override option disabled so i can
really be able to test authentic pages / offers.

Thank you
Andrew

**Comment by andreat-lj** [comment]
Hey Andrew,

To test the ads that are currently live, you may leave off the &override=#### parameter entirely (eg: http://www.marketdeal.com/cplplusdemo/?email=test-1214@finmc.com&name=test). When I use the demo to verify issues and confirm fixes, I will be utilizing &override=#### (eg: http://www.marketdeal.com/cplplusdemo/?email=test-1214@finmc.com&name=test&override=1166) to facilitate my testing of that specific offer. I have been including these testing links in the chain for convenience.

I apologize for any confusion I may have caused. Please let me know if you have any further questions or if you have any additional details for me. I'm not 100% clear on what your exact instructions are, so I will welcome any feedback or requests you may have for me.

Thank you!
Andrea

**Comment by davidm-finmc** [comment]
Peggy, 

Remove the override parameter and use a private/incognito window if you want to test that the correct offer is appearing when you click a market button.

Use the override parameter if you want to test changes to a specific offer, regardless of what is in rotation.

Also, you can use the override to test offers that are added to the very bottom of the getoffer.php file but haven’t been put into the live rotation yet.

Let me or White Debbie (Andrea) know if you have any questions about it.

Thanks,

Barbara

David Mound

IT Project Manager &

Chief Pastry Consumer

386.597.1004 ext. 4

 mailto:davidm@finmc.com davidm@finmc.com

Financial Media Corp

**Comment by andrewkhomski** [comment]
Harry and Andrea - thank you for your clarifications! I am good now...
