### ISSUE TITLE
On the 1222 - the "See How this Pattern Works" button doesn't work

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#37]
IE: On the 1222 - the "See How this Pattern Works" button doesn't work. This occurs on any browser (IE, Chrome and FF).

What it does every time when click on this button - it opens a new session page with the same content...

Here is how the urls links look like every time i click on this button:
http://safeclick.co/res/cplplus/ads/mmp/windfall-C/index.php?aid=276&po=1222&email=test-1215%40finmc.com&fn=test&ln=&phone=&oid=318&cid=4294368#

**Comment by andreat-lj** [comment]
This has been corrected.

**Comment by andrewkhomski** [comment]
I have verified teh fix and now it works properly. Closing.
