### ISSUE TITLE
On the 1223 - the "Download eBook" buttons shows next page with error

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#39]
Here is the error i get in all browsers:
{"error":1,"new_lead":0,"error_msg":"Email is not set","error_id":""} 

http://www.marketdeal.com/cplplusdemo/?email=test@test.com&fn=David&override=1223

See attached.
![issue-39-12212015](https://cloud.githubusercontent.com/assets/15894297/11946028/317a5f32-a824-11e5-9728-2b9cca2101f8.png)

**Comment by andreat-lj** [comment]
This has been corrected.

**Comment by andrewkhomski** [comment]
I have verified this fix and the issue is now resolved. Closing.
