### ISSUE TITLE
MOBILE (Android): GUI - image overlaps on 1118

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#5]
## MOBILE (Android): GUI - image overlaps on 1118

---

please see attached screenshot.
look the banner/image overlaps on 1118.

![issue-5](https://cloud.githubusercontent.com/assets/15894297/11519904/3576a5a4-986c-11e5-95d8-b6cdc613fd43.png)

**Comment by andreat-lj** [comment]
http://www.marketdeal.com/cplplusdemo/?email=test-1215@finmc.com&name=test&override=1118

Fixed overlap.

**Comment by andrewkhomski** [comment]
I have verified the fix in my Android phone (LG 4). PASS. Closing.
