### ISSUE TITLE
IE browser: 1160 - errors out when click on the Opt In Link

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#6]
## Server Error

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

**Comment by andreat-lj** [comment]
Cannot reproduce in IE.

http://www.marketdeal.com/cplplusdemo/?email=test@finmc.com&fn=test&override=1160
points to
http://safeclick.co/res/cplplus/redir/vig/reg_Nov2015.php/?aid=276&email=test@finmc.com&fn=test&ln=&phone=
which redirects to
http://www.markettrendsignal.com/secure/c39A-posc.php?a=29027-DA1-POSC&p=MTS

**Comment by andrewkhomski** [comment]
This is correct. At this point i also can't replicate the issue. Closing.

**Comment by andrewkhomski** [comment]
Thank you very much Andrea! I closed these Defects that not reproducible
any longer.

Thank you
Andrew
