### ISSUE TITLE
MOBILE (Android): GUI ALIGNMENT OF TEXT ON 1186

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#7]
## MOBILE (Android): GUI ALIGNMENT OF TEXT ON 1186

please look at the text ALIGNMENT on the ALIGNMENT. It is on 1186. See attached.

![issue-6](https://cloud.githubusercontent.com/assets/15894297/11520062/90a3d3c4-986d-11e5-8189-c07a78b42d05.png)

**Comment by andreat-lj** [comment]
http://www.marketdeal.com/cplplusdemo/?email=test-1215@finmc.com&name=test&override=1186

Fixed text alignment for mobile.

**Comment by andrewkhomski** [comment]
I have verified this fix in my android mobile phone. Issue is resolved. Closing.
