### ISSUE TITLE
MOBILE (Android): Need to scroll to the right to see the complete wording (1066).

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#8]
## MOBILE (Android): Need to scroll to the right to see the complete wording (1066).

![issue-7](https://cloud.githubusercontent.com/assets/15894297/11520087/df94dd66-986d-11e5-826c-5ebd032db102.png)

**Comment by andreat-lj** [comment]
Fixed. (Offer # 1166)
http://www.marketdeal.com/cplplusdemo/?email=test@finmc.com&name=test&override=1166

**Comment by andrewkhomski** [comment]
Yes, i just verified - the issue is resolved by making MarketDeal.com logo smaller.

**Comment by andrewkhomski** [comment]
Hi Andrea

The following are Defects i would give priority: IE: The "Sorry. This
seminar is over." message appear, when click on unique webinar link (1100) *#26
*

Chrome: Error "Confirm Form Re-submission" when click on BACK button (1205)
- #28 _New error on 1118 (Firefox) #_24*

I'll send you moein
Thank you
Andrew

**Comment by andreat-lj** [comment]
Hi Andrew,

Is the original issue corrected to your satisfaction? (http://www.marketdeal.com/cplplusdemo/?email=test@finmc.com&name=test&override=1166)

Thank you,
Andrea

**Comment by andrewkhomski** [comment]
Hey Andrea - this is correct. It is already closed.

Thank you
Andrew
