### ISSUE TITLE
IE: The "See how this pattern works" changes size (1166)

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/CPLPLUS#9]
## IE: The "See how this pattern works" changes size (1166)

If you hoover over this button on 1166 - observe how it changes its sie (gets jumpy).

![issue-8](https://cloud.githubusercontent.com/assets/15894297/11520129/55639e56-986e-11e5-9ecb-8feb5c4db4e2.png)

**Comment by andreat-lj** [comment]
http://www.marketdeal.com/cplplusdemo/?email=test-1215@finmc.com&name=test&override=1166

Fixed hover effect on button.

**Comment by andrewkhomski** [comment]
The issue is now fixed and verified - i have tested and closing it.
